### ISSUE TITLE
Zeroing Pigeon causes RIO crash

### ISSUE THREAD

**Issue by sraque** [CrossTheRoadElec/Phoenix-LabVIEW#1]
Working with the Phoenix Autonomous Example. Anytime zeroing the pigeon is activated, the code crashes (contact with RIO lost). The following snipping is the error in the DS window. 

![capture](https://user-images.githubusercontent.com/33502794/32583266-b4de7254-c4c0-11e7-8bcc-fd8d13d33f67.PNG)

**Comment by ozrien** [comment]
This was resolved a few beta releases ago (I think beta3).
