### ISSUE TITLE
CTRE_Phoenix_MotorControl_SetInverted.vi Context Help Wrong

### ISSUE THREAD

**Issue by vannaka** [CrossTheRoadElec/Phoenix-LabVIEW#5]
The context help for the **CTRE_Phoenix_MotorControl_SetInverted.vi** is showing the context help for CTRE_Phoenix_MotorControl_SetSensorPhase.

![ctre_phoenix_motorcontrol_setinverted vi context help](https://user-images.githubusercontent.com/5122956/50947442-ff5b4480-1463-11e9-9b40-59d01b702efe.PNG)

![setsensorphase context help](https://user-images.githubusercontent.com/5122956/50947516-5d882780-1464-11e9-9919-24855c6e6a1d.PNG)

**Comment by JCaporuscio** [comment]
This is fixed on master, and will be picked up in the next installer release.
